In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/CEO3.csv', encoding='cp949')
df

,number,firm,publishing,country,text,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 450,Unnamed: 451,Unnamed: 452,Unnamed: 453,Unnamed: 454,Unnamed: 455,Unnamed: 456,Unnamed: 457,Unnamed: 458,Unnamed: 459
0,2,Amorepacific,1,Korea,We will use beauty to change the world and bec...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,Amorepacific,3,Korea,AMOREPACIFC Group will endeavor to become a gr...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,502,Amorepacific,4,Korea,AMOREPACIFIC Group has been pursuing the path ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,Asiana Airlines,1,Korea,This year marks the 25th anniversary of the es...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,Asiana Airlines,2,Korea,"Since the inception, Asiana Airlines has pledg...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,486,Wyndham Worldwide,1,USA,Acting with integrity and providing a great e...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,487,Wyndham Worldwide,2,USA,With\ta\tunique\tglobal\tportfolio\tthat\tincl...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375,488,Wyndham Worldwide,3,USA,With\tthe\twidest\trange\tof\tplaces\tto\tstay...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,490,Xilinx,3,USA,"These are exciting times for Xilinx, and the e...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,623,Xilinx,4,USA,These are exciting times at Xilinx. Systems an...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
texts = df.text

In [6]:
from nltk.tokenize import RegexpTokenizer # 정규표현식 사용 정제

tokenizer = RegexpTokenizer(r'\w+')

In [7]:
from nltk.stem import WordNetLemmatizer # 표제어
lemmatizer = WordNetLemmatizer()

In [8]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rkdtk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
from nltk.corpus import stopwords
stop_words = nltk.corpus.stopwords.words('english')

In [10]:
stop_words.extend([])

In [12]:
stop_words[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [13]:
from nltk import wordnet

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rkdtk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [17]:
preprocessed_texts = []

for text in texts.values:
    tokenized_text = tokenizer.tokenize(text.lower()) # 소문자로 변경해서 토큰화
    # 토큰화된 텍스트를 표제어 구성된 리스트 생성
    lemmatized_text = [lemmatizer.lemmatize(token) for token in tokenized_text] # 표제어로 만듬 사전에 등제된 공통 단어로?
    stopped_text = [token for token in lemmatized_text if token not in stop_words]
    # 불용어가 아닌 토큰이라면, 표제어 리스트에서 토큰을 추출해 리스트로 만들기
    preprocessed_texts.append(stopped_text)

In [22]:
from collections import Counter

tokens = []
for text in preprocessed_texts:
    tokens.extend(text)
    
counted_tokens = Counter(tokens)
top_20 = counted_tokens.most_common(20)
top_20

[('business', 1534),
 ('company', 1445),
 ('year', 1159),
 ('management', 969),
 ('global', 953),
 ('growth', 938),
 ('sustainability', 907),
 ('customer', 890),
 ('also', 766),
 ('value', 755),
 ('new', 752),
 ('community', 722),
 ('world', 713),
 ('ha', 700),
 ('product', 683),
 ('social', 669),
 ('employee', 658),
 ('stakeholder', 651),
 ('effort', 637),
 ('u', 635)]